# Generated by Django 2.1.4 on 2019-10-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('1', '한식'), ('2', '일식'), ('3', '중식'), ('4', '분식'), ('5', '야식'), ('6', '아시안')], max_length=20),
        ),
    ]
